### ISSUE TITLE
Consider a refactor to make adding forecasts easier

### ISSUE THREAD

**Issue by irrationalagent** [mozilla/forecasting#41]
The prophet model has only a few useful parameters, and takes training data of a standard [date, measure] format. It also outputs a standard format for the forecast. Ideally, it should be easy enough to provide an arbitrary time-series-producing query and set of model parameters and then write the resulting forecast to a table.

Looking at the code, 

The queries that generate the training data are hardcoded here, in two separate objects for desktop and non-desktop:
https://github.com/mozilla/forecasting/blob/main/simpleprophet/simpleprophet/data.py

And the specs for the models are hardcoded here: https://github.com/mozilla/forecasting/blob/main/simpleprophet/simpleprophet/models.py

The start(?) dates of each model are hardcoded here:
https://github.com/mozilla/forecasting/blob/main/simpleprophet/simpleprophet/pipeline.py

So to add a forecast, you have to go in and change each of these files, which is a bit cumbersome. 

It might be more ergonomic if we pulled both the queries for the training data and the model parameters out into individual files (one per forecast model) that sit in e.g. a /forecasts directory, and then rewrote pipeline.py to run a forecast for each file it finds. Then, adding a forecast would be as easy as merging a PR with a file containing a query + (optional) model parameters into the /forecasts directory. 

Here's a the workflow I'm imagining:

1. To add a forecast, produce a yaml file with fields: query, yearly_seasonality, changepoint_prior_scale, seasonality_prior_scale, seasonality_mode, holidays. We could also separate the query and model parameters into .sql and .yaml files respectively if needed. Technically all of the model parameters are optional - they all have defaults in the function that actually fits the forecast.
2. We modify `pipeline.py` to run through each file, produce the forecast specified, and write the results to a single BQ table that contains all the forecasts (it can be the same format we have now in simpleprophet_forecasts). 

@xluo-ds and others... what do you think about this? it could make it considerably easier to add forecasts for any segment of interest, but it would also be a fair amount of work, I think. I'd be willing to take a shot at if people would be OK with it...

**Comment by jklukas** [comment]
cc @gkabbz

**Comment by jklukas** [comment]
In general, codifying models in yaml rather than in python sounds like a good thing. I also like the idea here that we're able to keep all configuration together on a per-model basis.

From the production running perspective, note that we currently have [three separate jobs that run in Airflow for forecasting](https://workflow.telemetry.mozilla.org/tree?dag_id=kpi_forecasts): one each for desktop, mobile, and FxA. Each of those depend on a separate ETL pathway, and we allow the forecasting process to proceed based on when the upstream ETL completes. I would like to maintain an interface where we can have an entrypoint for Airflow that can specify running a single of these categories.

Are all of the forecasts currently codified still relevant? Do we care about FxA forecasts anymore?

**Comment by irrationalagent** [comment]
I started on this. I think I'm 75% of the way there, but I haven't actually tested anything yet and there are a couple things I haven't figured out the best way to handle yet. I'll try to have a PR up this week. In the meantime here's how I've structured the yaml file, to get some early feedback. The example below would be intended to replace all the per-product mobile MAU forecasts that are already in the repo (some of the parameter values may not be right, but just to illustrate). This would be a case where the yaml file is a bit more involved - I think in most cases the query would return a more basic time series so it would be a lot shorter.

```yaml
---
# one query per file, each query may define multiple possible forecasts
# note that this file defines 16 separate forecasts: 2 metrics (global_mau, tier1_mau) * 8 segment levels (one level for each mobile product)
query: >
  SELECT
      submission_date as date,
      SUM(mau) AS global_mau,
      SUM(tier1_mau) AS tier1_mau,
      product
  FROM
      `moz-fx-data-shared-prod.telemetry.firefox_nondesktop_exact_mau28_by_product_v1`
  GROUP BY
      submission_date,
      product
  ORDER BY
      date
# these default parameter values apply to every model unless explicitly overwritten in the segment section below.
# note that any parameters that aren't specified anywhere in the yaml file will get the prophet defaults
default_changepoint_prior_scale: 0.0005
# optional, identifies the columns in the query result that define segments that need to be forecasted separately.
# the sub-fields are the levels of the segment (e.g. would be `Windows`, `Linux` etc if the segment column was `os`)
# the segment levels only need to be specified if the model parameters for that level need to be different than the default values above
# otherwise, every level of every segment column that is returned by the query will be forecasted with the provided default values (or prophet defaults if none are provided). 
# As such some of the levels below are shown for illustration; they wouldn't have to be explicitly specified since they would be covered by the defaults. 
segments:
  - product:
    - Fennec: {
      seasonality_prior_scale: 0.001,
      seasonality_mode: multiplicative
    }
    - Focus iOS: {
      changepoint_prior_scale: 0.0005
    }
    - Focus Android: {
      changepoint_prior_scale: 0.005
    }
    - Firefox iOS: {
      changepoint_prior_scale: 0.005,
      seasonality_prior_scale: 0.001,
      seasonality_mode: multiplicative
    }
    - Fenix: {
      changepoint_prior_scale: 0.0005
    }
    - Firefox Lite: {
      changepoint_prior_scale: 0.0005
    }
    - Firefox Echo: {
      changepoint_prior_scale: 0.0005
    }
    - Lockwise Android: {
      seasonality_prior_scale: 0.001,
      seasonality_mode: multiplicative
    }
# identifies the columns from the query result that will actually be forecasted
metrics:
  - global_mau
  - tier1_mau
# optional re-names of the metrics above (need to be in same order; this is mainly for backwards-compatibility for current MAU forecasts)
metrics_names:
  - Global MAU
  - Tier1 MAU
# the `datasource` for the DAG: desktop, mobile or fxa
datasource: mobile
```

> Are all of the forecasts currently codified still relevant? Do we care about FxA forecasts anymore?

We could probably get rid of them. I'll do that as a part of this

**Comment by jklukas** [comment]
One note on the structure here:

```
segments:
  - product:
    - Fennec: {
      seasonality_prior_scale: 0.001,
      seasonality_mode: multiplicative
    }
```

I would expect this to be either (simplified):

```
segments:
  product:
    Fennec: { ... }
```

or something more verbose and structured but more extensible:

```
segments:
  - field: product
    slices:
      - value: Fennec
        parameters: { ... }
```
